---
- name: Download my personal deb-get repo
  git:
    repo: "https://github.com/GHMusicalCoder/deb-get.git"
    dest: "/home/{{ lookup('env','USER') }}/Development/deb-get"

- name: Install deb-get
  shell: curl -sL https://raw.githubusercontent.com/wimpysworld/deb-get/main/deb-get | sudo -E bash -s install deb-get
  become: yes

# install personal installers for deb-get
- name: create additional deb-get install folders in /etc
  become: yes
  file:
    path: "{{ item }}"
    state: directory
  with_items: "{{ deb_get_dirs }}"
  when: deb_get_dirs is defined

# copy personal deb-get installers
- name: copy deb-get_submitted for deb-get usage
  become: yes
  copy:
    src: files/deb-get_submitted
    dest: "/etc/deb-get.d/additional_functions/"
    mode: 0644


