---
- name: Ansible Installation of software
  hosts:  localhost
  become: no
  vars_files:
    - "config/directories.yaml"
    - "config/applications.yaml"
    - "config/other_vars.yaml"
  pre_tasks:
    - name: update repositories
      become: yes
      apt: update_cache=yes
      changed_when: false
  tasks:
    - include: tasks/system.yaml
    # - include: tasks/apps.yaml
  post_tasks:
    - name: fix any broken installs
      become: yes
      apt:
        name: "*"
        state: fixed
        autoclean: yes
    - name: autoremove and purge apt packages - fix broken installs
      become: yes
      apt:
        autoremove: yes
        purge: yes