---
- name: Setting up system and personal directories
  include: tasks/system/directories.yaml

# github credentials
- name: Setting up github credentials
  include: tasks/system/github_config.yaml

# gitlab credentials
- name: Setting up github credentials
  include: tasks/system/gitlab_config.yaml


# deb-get
# - name: install deb-get (personal forked) repo
#   include: tasks/system/deb-get.yaml


