---
- name: Setting up system and personal directories
  include: tasks/system/directories.yaml

# github credentials
- name: Setting up github credentials
  include: tasks/system/github_config.yaml

# gitlab credentials
- name: Setting up github credentials
  include: tasks/system/gitlab_config.yaml

# additional installers
- name: Setting up additional installation programs (deb-get / git repos / cmk-get)
  include: tasks/system/3rd_party_installers.yaml



