---
- name: install virtual machine apt packages
  become: yes
  ansible.builtin.apt:
    pkg: "{{ virt_machine_apps }}"
    state: present
  when: virt_machine_apps is defined

- name: adding user to libvirt group
  become: yes
  user:
    name: "{{ lookup('env','USER') }}"
    groups: libvirt
    append: yes

- name: install quickemu via deb-get
  shell: sudo deb-get install quickemu quickgui

