#!/usr/bin/env bash

function backup_doctor() {
    declare -a FOLDERS=("calibre" "Documents" "Downloads" "Music" "Pictures" "Temp" "Videos" "Work")
    RSYNC_CMD="rsync -auv"
    FROM="/home/christopher/"
    TO="/mnt/crypt/Backups/the-doctor/"
    for f in ${FOLDERS[@]}
    do 
        if [[ "${f}" == "calibre" ]]; then
            echo "Backing Calibre Library up to the NAS"
            ${RSYNC_CMD} ${FROM}Calibre\ Library/* ${TO}Calibre\ Library
        else
            echo "Backing ${f} up to the NAS"
            ${RSYNC_CMD} ${FROM}${f}/* ${TO}${f}
        fi
    done
}

function update_crypt_backup() {
    #backups
    FROM="/mnt/crypt/Backups/"
    TO="/media/christopher/ARCHIVAL/Backups/"
    RSYNC_CMD="rsync -auv"
    if [[ -d "${TO}" ]]; then
        declare -a FOLDERS=("db_backups" "satelite-5" "the-doctor" "the-tardis")
        for f in ${FOLDERS[@]}
        do
            echo "Backing ${f} up to the NAS"
            if [[ "${f}" == "the-doctor" ]]; then
                ${RSYNC_CMD} ${FROM}${f}/* ${TO}${f}-2207
            else
                ${RSYNC_CMD} ${FROM}${f}/* ${TO}${f}
            fi
        done

        #unsorted
        FROM="/mnt/crypt/Unsorted/"
        TO="/media/christopher/ARCHIVAL/Unsorted/"
        declare -a FOLDERS=("CKMusicDrive" "DaniMusicDrive" "NewStuff" "StorageOne" "StorageTwo" "StorageThree")
        for f in ${FOLDERS[@]}
        do
            echo "Backing ${f} up to the NAS"
            if [[ "${f}" == "CKMusicDrive" ]] || [[ "${f}" == "DaniMusicDrive" ]]; then
                ${RSYNC_CMD} ${FROM}${f}/* ${TO}DJDrives
            else
                ${RSYNC_CMD} ${FROM}${f}/* ${TO}${f}
            fi
        done
    else
        echo "Your Media Storage Archive is missing - make sure its plugged in and turned on..."
    fi
}

function update_vault_backup() {
    RSYNC_CMD="rsync -auv"
    FROM="/mnt/vault/"
    TO="/media/christopher/ARCHIVAL/vault"
    if [[ -d "${TO}" ]]; then
        ${RSYNC_CMD} ${FROM}* ${TO}
    else
        echo "Your Media Storage Archive is missing - make sure its plugged in and turned on..."
    fi
}