#!/usr/bin/env bash

function deb_master-pdf-editor() {
    if [ "${ACTION}" != "prettylist" ]; then
        URL=$(curl -s -S "https://code-industry.net/get-master-pdf-editor-for-ubuntu/?download" | grep -Eo "href=\"https://code-industry.net/public/.*\.deb" | cut --complement -c -6)
        VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f6)"
    fi
    PRETTY_NAME="Master PDF Editor"
    WEBSITE="https://code-industry.net/free-pdf-editor/"
    SUMMARY="Edit PDF files in Linux. It enables you to create, edit, view and print interactive PDF documents."
}

function deb_lbry() {
    get_github_releases "https://api.github.com/repos/lbryio/lbry-desktop/releases/latest"
    if [ "${ACTION}" != "prettylist" ]; then
        URL=$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | cut -d'"' -f4)
        VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f8 | tr -d v)"
    fi
    PRETTY_NAME="LBRY Desktop Viewer"
    WEBSITE="https://lbry.com/"
    SUMMARY="Desktop client for the LBRY digital content network."
}

function deb_ivpn() {
    get_github_releases "https://api.github.com/repos/ivpn/desktop-app/releases/latest"
    if [ "${ACTION}" != "prettylist" ]; then
        URL=$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | cut -d'"' -f4)
        VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f8 | tr -d v)"
    fi
    PRETTY_NAME="IVPN for Desktop"
    WEBSITE="https://www.ivpn.net/"
    SUMMARY="VPN Service that does not keep logs."
}

function deb_beyond-compare() {
    if [ "${ACTION}" != "prettylist" ]; then
        BASE_VER=$(curl -s -S https://www.scootersoftware.com/download.php | grep -Eo "Current Version:.*, released" | cut --complement -c -23 | sed 's/\,\ build\ /\./' | sed 's/\, released/\_/')
        # = 4.4.3.26655
        URL="https://www.scootersoftware.com/bcompare-${BASE_VER}amd64.deb"
        VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f6)"
    fi
    PRETTY_NAME="Beyond Compare"
    WEBSITE="https://www.scootersoftware.com/"
    SUMMARY="GUI Diff and Merge tool"
}

function deb_sparrow-wallet() {
    get_github_releases "https://api.github.com/repos/sparrowwallet/sparrow/releases/latest"
    if [ "${ACTION}" != "prettylist" ]; then
        URL=$(grep "browser_download_url.*.deb" "${CACHE_DIR}/${APP}.json" | cut -d'"' -f4)
        VERSION_PUBLISHED="$(echo "${URL}" | cut -d'/' -f8 | tr -d v)"
    fi
    PRETTY_NAME="Sparrow Wallet"
    WEBSITE="https://sparrowwallet.com/"
    SUMMARY="Bitcoin Wallet"
 
}
